apiVersion: apps/v1
kind: Deployment
metadata:
  name: loggeneratordeployment
  labels:
    app: loggenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loggenerator
  template:
    metadata:
      labels:
        app: loggenerator
    spec:
      containers:
        - name: loggenerator
          image: hari/loggenerator:v5
          imagePullPolicy: Always
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: log-path
              mountPath: /var/log/dummyapp
      volumes:
        - name: log-path
          hostPath:
            path: /var/log/dummyapp

